<?php

use Illuminate\Database\Seeder;

class ConfiguratorGeneratedJsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('configurator_generated_js')->delete();
        
        \DB::table('configurator_generated_js')->insert(array (
            0 => 
            array (
                'id' => 33,
                'publisher_id' => 24,
                'configurator_unique_id' => '32a508e578e8c74c2f4b62c0f9959b4b',
                'piwik_website_id' => '47',
                'piwik_website_name' => 'FIND - RECETTES - Hellosearch',
                'partner_name' => '',
                'product_name' => '',
                'product_sub_id' => '',
                'publisher_configurator_generated_js_no' => 1,
                'is_delete' => 0,
                'created_at' => '2016-03-25 10:50:07',
                'updated_at' => '2016-03-25 10:50:07',
            ),
            1 => 
            array (
                'id' => 34,
                'publisher_id' => 25,
                'configurator_unique_id' => 'c0159a716547582912e64a69d88ab350',
                'piwik_website_id' => '48',
                'piwik_website_name' => 'FIND - WIKIMOT - Hellosearch',
                'partner_name' => '',
                'product_name' => '',
                'product_sub_id' => '',
                'publisher_configurator_generated_js_no' => 1,
                'is_delete' => 0,
                'created_at' => '2016-03-25 10:52:55',
                'updated_at' => '2016-03-25 10:52:55',
            ),
            2 => 
            array (
                'id' => 35,
                'publisher_id' => 6,
                'configurator_unique_id' => '296632c12abe3b0a7e6cedb3c7a53082',
                'piwik_website_id' => '49',
                'piwik_website_name' => 'FIND - Hellosearch',
                'partner_name' => '',
                'product_name' => '',
                'product_sub_id' => '',
                'publisher_configurator_generated_js_no' => 1,
                'is_delete' => 0,
                'created_at' => '2016-03-25 10:53:20',
                'updated_at' => '2016-03-25 10:53:20',
            ),
            3 => 
            array (
                'id' => 37,
                'publisher_id' => 26,
                'configurator_unique_id' => 'c69afa804e2e3d971f4d2ae75adf633a',
                'piwik_website_id' => '51',
                'piwik_website_name' => 'RAFO - 1',
                'partner_name' => '',
                'product_name' => '',
                'product_sub_id' => '',
                'publisher_configurator_generated_js_no' => 1,
                'is_delete' => 0,
                'created_at' => '2016-03-26 18:57:16',
                'updated_at' => '2016-03-26 18:57:16',
            ),
            4 => 
            array (
                'id' => 38,
                'publisher_id' => 27,
                'configurator_unique_id' => '15ea33ef9dbfc937b588e1421472471e',
                'piwik_website_id' => '52',
                'piwik_website_name' => 'TESTPARTNER - testproduct',
                'partner_name' => '',
                'product_name' => '',
                'product_sub_id' => '',
                'publisher_configurator_generated_js_no' => 1,
                'is_delete' => 0,
                'created_at' => '2016-03-26 20:52:40',
                'updated_at' => '2016-03-26 20:52:40',
            ),
            5 => 
            array (
                'id' => 39,
                'publisher_id' => 27,
                'configurator_unique_id' => '4f0dfca902ee7c1e5bc1ac54c3eb2e93',
                'piwik_website_id' => '53',
                'piwik_website_name' => 'TESTPARTNER - test',
                'partner_name' => '',
                'product_name' => '',
                'product_sub_id' => '',
                'publisher_configurator_generated_js_no' => 2,
                'is_delete' => 0,
                'created_at' => '2016-03-26 20:56:15',
                'updated_at' => '2016-03-26 20:56:15',
            ),
            6 => 
            array (
                'id' => 40,
                'publisher_id' => 27,
                'configurator_unique_id' => '530fc00db97f057184929907b95316f9',
                'piwik_website_id' => '54',
                'piwik_website_name' => 'TESTPARTNER - Test prod',
                'partner_name' => '',
                'product_name' => '',
                'product_sub_id' => '',
                'publisher_configurator_generated_js_no' => 3,
                'is_delete' => 0,
                'created_at' => '2016-03-27 19:46:21',
                'updated_at' => '2016-03-27 19:46:21',
            ),
            7 => 
            array (
                'id' => 41,
                'publisher_id' => 26,
                'configurator_unique_id' => '1986545c3dbd2f8fb0b11fed9f91e522',
                'piwik_website_id' => '55',
                'piwik_website_name' => 'RAFO - product1',
                'partner_name' => '',
                'product_name' => '',
                'product_sub_id' => '',
                'publisher_configurator_generated_js_no' => 2,
                'is_delete' => 0,
                'created_at' => '2016-03-29 17:37:07',
                'updated_at' => '2016-03-29 17:37:07',
            ),
            8 => 
            array (
                'id' => 42,
                'publisher_id' => 26,
                'configurator_unique_id' => '1986545c3dbd2f8fb0b11fed9f91e522',
                'piwik_website_id' => '56',
                'piwik_website_name' => 'RAFO - product1',
                'partner_name' => '',
                'product_name' => '',
                'product_sub_id' => '',
                'publisher_configurator_generated_js_no' => 3,
                'is_delete' => 0,
                'created_at' => '2016-03-29 17:38:17',
                'updated_at' => '2016-03-29 17:38:17',
            ),
            9 => 
            array (
                'id' => 43,
                'publisher_id' => 26,
                'configurator_unique_id' => '1986545c3dbd2f8fb0b11fed9f91e522',
                'piwik_website_id' => '57',
                'piwik_website_name' => 'RAFO - product1',
                'partner_name' => '',
                'product_name' => '',
                'product_sub_id' => '',
                'publisher_configurator_generated_js_no' => 4,
                'is_delete' => 0,
                'created_at' => '2016-03-29 17:38:17',
                'updated_at' => '2016-03-29 17:38:17',
            ),
            10 => 
            array (
                'id' => 44,
                'publisher_id' => 26,
                'configurator_unique_id' => '1986545c3dbd2f8fb0b11fed9f91e522',
                'piwik_website_id' => '58',
                'piwik_website_name' => 'RAFO - product1',
                'partner_name' => '',
                'product_name' => '',
                'product_sub_id' => '',
                'publisher_configurator_generated_js_no' => 5,
                'is_delete' => 0,
                'created_at' => '2016-03-29 18:36:29',
                'updated_at' => '2016-03-29 18:36:29',
            ),
            11 => 
            array (
                'id' => 45,
                'publisher_id' => 26,
                'configurator_unique_id' => '1986545c3dbd2f8fb0b11fed9f91e522',
                'piwik_website_id' => '59',
                'piwik_website_name' => 'RAFO - product1',
                'partner_name' => '',
                'product_name' => '',
                'product_sub_id' => '',
                'publisher_configurator_generated_js_no' => 6,
                'is_delete' => 0,
                'created_at' => '2016-03-29 18:39:24',
                'updated_at' => '2016-03-29 18:39:24',
            ),
            12 => 
            array (
                'id' => 46,
                'publisher_id' => 28,
                'configurator_unique_id' => 'dc1d79ea7d82ecf3d08d1ad7b0ddbb8b',
                'piwik_website_id' => '60',
                'piwik_website_name' => 'TESTPARTNERSAM - product1 - subid1',
                'partner_name' => 'TESTPARTNERSAM',
                'product_name' => 'product1',
                'product_sub_id' => 'subid1',
                'publisher_configurator_generated_js_no' => 1,
                'is_delete' => 0,
                'created_at' => '2016-03-29 21:40:04',
                'updated_at' => '2016-03-29 21:40:04',
            ),
            13 => 
            array (
                'id' => 47,
                'publisher_id' => 28,
                'configurator_unique_id' => '6980412fd27c875987841335c261b694',
                'piwik_website_id' => '61',
                'piwik_website_name' => 'TESTPARTNERSAM - product2 - subid2',
                'partner_name' => 'TESTPARTNERSAM',
                'product_name' => 'product2',
                'product_sub_id' => 'subid2',
                'publisher_configurator_generated_js_no' => 2,
                'is_delete' => 0,
                'created_at' => '2016-03-29 21:43:46',
                'updated_at' => '2016-03-29 21:43:46',
            ),
            14 => 
            array (
                'id' => 48,
                'publisher_id' => 29,
                'configurator_unique_id' => 'f31b91bc6d0c253d8521a439f7183d11',
                'piwik_website_id' => '62',
                'piwik_website_name' => 'TEST - test',
                'partner_name' => 'TEST',
                'product_name' => 'test',
                'product_sub_id' => '',
                'publisher_configurator_generated_js_no' => 1,
                'is_delete' => 0,
                'created_at' => '2016-03-30 12:29:16',
                'updated_at' => '2016-03-30 12:29:16',
            ),
            15 => 
            array (
                'id' => 49,
                'publisher_id' => 26,
                'configurator_unique_id' => '123647fe94c3af33e72f07da156f95d3',
                'piwik_website_id' => '63',
                'piwik_website_name' => 'RAFO - GreatDeals',
                'partner_name' => 'RAFO',
                'product_name' => 'GreatDeals',
                'product_sub_id' => '',
                'publisher_configurator_generated_js_no' => 7,
                'is_delete' => 0,
                'created_at' => '2016-03-30 12:44:56',
                'updated_at' => '2016-03-30 12:44:56',
            ),
            16 => 
            array (
                'id' => 50,
                'publisher_id' => 26,
                'configurator_unique_id' => '123647fe94c3af33e72f07da156f95d3',
                'piwik_website_id' => '64',
                'piwik_website_name' => 'RAFO - GreatDeals',
                'partner_name' => 'RAFO',
                'product_name' => 'GreatDeals',
                'product_sub_id' => '',
                'publisher_configurator_generated_js_no' => 8,
                'is_delete' => 0,
                'created_at' => '2016-03-30 13:03:20',
                'updated_at' => '2016-03-30 13:03:20',
            ),
            17 => 
            array (
                'id' => 51,
                'publisher_id' => 29,
                'configurator_unique_id' => 'fe30e42c9905e403c2a73d0459bf1f03',
                'piwik_website_id' => '65',
                'piwik_website_name' => 'TEST - Test Product',
                'partner_name' => 'TEST',
                'product_name' => 'Test Product',
                'product_sub_id' => '',
                'publisher_configurator_generated_js_no' => 2,
                'is_delete' => 0,
                'created_at' => '2016-03-31 12:06:16',
                'updated_at' => '2016-03-31 12:06:16',
            ),
            18 => 
            array (
                'id' => 52,
                'publisher_id' => 29,
                'configurator_unique_id' => 'fe30e42c9905e403c2a73d0459bf1f03',
                'piwik_website_id' => '66',
                'piwik_website_name' => 'TEST - Test Product',
                'partner_name' => 'TEST',
                'product_name' => 'Test Product',
                'product_sub_id' => '',
                'publisher_configurator_generated_js_no' => 3,
                'is_delete' => 0,
                'created_at' => '2016-03-31 12:06:17',
                'updated_at' => '2016-03-31 12:06:17',
            ),
            19 => 
            array (
                'id' => 53,
                'publisher_id' => 31,
                'configurator_unique_id' => '8d0f4b70407ee32b475c0d57f6c3e732',
                'piwik_website_id' => '67',
                'piwik_website_name' => 'TESTPARTNERSAMAGAIN - testproduct - testsubid',
                'partner_name' => 'TESTPARTNERSAMAGAIN',
                'product_name' => 'testproduct',
                'product_sub_id' => 'testsubid',
                'publisher_configurator_generated_js_no' => 1,
                'is_delete' => 0,
                'created_at' => '2016-04-02 15:38:55',
                'updated_at' => '2016-04-02 15:38:55',
            ),
            20 => 
            array (
                'id' => 54,
                'publisher_id' => 32,
                'configurator_unique_id' => '51178626fff54acff1b67baca9cafc28',
                'piwik_website_id' => '68',
                'piwik_website_name' => 'ADONADS - DealsForYou - efg',
                'partner_name' => 'ADONADS',
                'product_name' => 'DealsForYou',
                'product_sub_id' => 'efg',
                'publisher_configurator_generated_js_no' => 1,
                'is_delete' => 0,
                'created_at' => '2016-04-22 11:51:08',
                'updated_at' => '2016-04-22 11:51:08',
            ),
            21 => 
            array (
                'id' => 55,
                'publisher_id' => 33,
                'configurator_unique_id' => '53fbc2b1b51629975ab8c669bb7c7214',
                'piwik_website_id' => '69',
                'piwik_website_name' => 'AZIM - test - efg',
                'partner_name' => 'AZIM',
                'product_name' => 'test',
                'product_sub_id' => 'efg',
                'publisher_configurator_generated_js_no' => 1,
                'is_delete' => 0,
                'created_at' => '2016-05-16 08:48:06',
                'updated_at' => '2016-05-16 08:48:06',
            ),
            22 => 
            array (
                'id' => 56,
                'publisher_id' => 33,
                'configurator_unique_id' => '61cdf60bc4c7aa094d45c3ba5e5366b4',
                'piwik_website_id' => '0',
                'piwik_website_name' => 'AZIM - test - efg',
                'partner_name' => 'AZIM',
                'product_name' => 'test',
                'product_sub_id' => 'efg',
                'publisher_configurator_generated_js_no' => 2,
                'is_delete' => 0,
                'created_at' => '2016-05-26 03:07:51',
                'updated_at' => '2016-05-26 03:07:51',
            ),
            23 => 
            array (
                'id' => 57,
                'publisher_id' => 33,
                'configurator_unique_id' => '7c4794ca5ecd3cd6e000cba4c0da864a',
                'piwik_website_id' => '0',
                'piwik_website_name' => 'AZIM - test - efg',
                'partner_name' => 'AZIM',
                'product_name' => 'test',
                'product_sub_id' => 'efg',
                'publisher_configurator_generated_js_no' => 3,
                'is_delete' => 0,
                'created_at' => '2016-05-26 03:08:37',
                'updated_at' => '2016-05-26 03:08:37',
            ),
            24 => 
            array (
                'id' => 58,
                'publisher_id' => 32,
                'configurator_unique_id' => '7b5b176053179f227ce578ada2d28aae',
                'piwik_website_id' => '0',
                'piwik_website_name' => 'ADONADS - 2',
                'partner_name' => 'ADONADS',
                'product_name' => '',
                'product_sub_id' => '',
                'publisher_configurator_generated_js_no' => 2,
                'is_delete' => 0,
                'created_at' => '2016-06-01 16:27:08',
                'updated_at' => '2016-06-01 16:27:08',
            ),
            25 => 
            array (
                'id' => 59,
                'publisher_id' => 34,
                'configurator_unique_id' => '42efb6fadc0b538dd4cf1c00584de7e1',
                'piwik_website_id' => '0',
                'piwik_website_name' => 'MYMEDIA - name - efg',
                'partner_name' => 'MYMEDIA',
                'product_name' => 'name',
                'product_sub_id' => 'efg',
                'publisher_configurator_generated_js_no' => 1,
                'is_delete' => 0,
                'created_at' => '2016-06-09 04:32:47',
                'updated_at' => '2016-06-09 04:32:47',
            ),
            26 => 
            array (
                'id' => 60,
                'publisher_id' => 35,
                'configurator_unique_id' => '8fe92eeea149183501ed3bfc0ea0dfd3',
                'piwik_website_id' => '0',
                'piwik_website_name' => 'IRIS MEDIA INC. - AdSupply - efg',
                'partner_name' => 'IRIS MEDIA INC.',
                'product_name' => 'AdSupply',
                'product_sub_id' => 'efg',
                'publisher_configurator_generated_js_no' => 1,
                'is_delete' => 0,
                'created_at' => '2016-06-10 16:16:44',
                'updated_at' => '2016-06-10 16:16:44',
            ),
            27 => 
            array (
                'id' => 61,
                'publisher_id' => 33,
                'configurator_unique_id' => '413eb4159af203fb2f9e48b1533f1349',
                'piwik_website_id' => '0',
                'piwik_website_name' => 'BLACKSWAN VENTURES - Search Results - EFG',
                'partner_name' => 'BLACKSWAN VENTURES',
                'product_name' => 'Search Results',
                'product_sub_id' => 'EFG',
                'publisher_configurator_generated_js_no' => 4,
                'is_delete' => 0,
                'created_at' => '2016-06-20 15:53:26',
                'updated_at' => '2016-06-20 15:53:26',
            ),
        ));
        
        
    }
}
